### ISSUE TITLE
npm install shasum check fail

### ISSUE THREAD

**Issue by yaru22** [pilwon/barbeque#3]
Whenever I try to install barbeque via npm, I get the following error.

Maybe republishing it would solve the problem?

```
npm ERR! Error: shasum check failed for /var/folders/jx/ld05kdhs3313jgttdhg6p1qh0000gn/T/npm-52119-dQefrkPO/1392996641155-0.8323704020585865/tmp.tgz
npm ERR! Expected: 848504c9778a4c0c6d73128be9f28adba6647f29
npm ERR! Actual:   c1b435622582d05a98c04170bd2cf5eea8412ef7
npm ERR! From:     https://registry.npmjs.org/barbeque/-/barbeque-0.2.2.tgz
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/sha/index.js:38:8
npm ERR!     at ReadStream.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/sha/index.js:85:7)
npm ERR!     at ReadStream.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/isaacs/npm/issues>

npm ERR! System Darwin 11.4.2
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/brianpark/workspace/exactmedia/api
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.24
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/brianpark/workspace/exactmedia/api/npm-debug.log
npm ERR! not ok code 0
```

**Comment by pilwon** [comment]
@yaru22 Re-published as v0.2.3
